Bugfix for ValueError
*WARNING, revealed that dictionary parser wasn't working correctly*. For example, pronoun list only contained 'their'.

According to Dan, the previous code passed *all* of the buckets simultaneously, which is obviously greater than the 'eachstemword, eachstembuckets' on the left side of the for loop

The following error code resulted:

C:\Python64\venv\enron\Scripts\python.exe C:/Users/Eric/PycharmProjects/EnronClustering/LEWC_dict.py
Traceback (most recent call last):
  File "C:/Users/Eric/PycharmProjects/EnronClustering/LEWC_dict.py", line 129, in <module>
    bucketCounts = parseDocuments(buckets)
  File "C:/Users/Eric/PycharmProjects/EnronClustering/LEWC_dict.py", line 86, in parseDocuments
    for eachStemWord, stemBuckets in buckets['stem']:  # Stem processing
ValueError: too many values to unpack

Process finished with exit code 1